#' Fixtures data
#'
#' This is just a test dataset which comes from the original mapbox library.
#'
#' @format an `sf` object with a 1000 points. Each of them is part of a group, indicated by variable k (generated by a k-means algorithm).
#' @source https://github.com/mapbox/concaveman/blob/master/test/fixtures/points-1k.json
"points"
