# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_concaveman
#' @noRd 
rcpp_concaveman <- function(xy, hull_in, concavity, length_threshold) {
    .Call(`_concaveman_rcpp_concaveman`, xy, hull_in, concavity, length_threshold)
}

